pfsense_ip_wan: "192.168.10.1"
pfsense_ip_lan: "192.168.1.21"
#{{ root_password_hash }}
#{{ vpn_user_password_hash }}
#{{ asn_token }}
#{{ maxmind_account }}
#{{ maxmind_key }}
#{{ oinkcode }}
#{{ maxmind_geoipdb_uid }}
#{{ maxmind_geoipdb_key }}

