- name: Deploy pfSense custom config
  hosts: pfsense
  become: false
  gather_facts: false

  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Instaleaza pachetul pfSense-pkg-suricata
      ansible.builtin.shell:  |
        pkg install -y pfSense-pkg-suricata

    - name: Instaleaza pachetul pfBlockerNG-devel
      ansible.builtin.shell:  |
        pkg install -y pfSense-pkg-pfBlockerNG-devel

    - name: Instaleaza pachetul openvpn-client-export
      ansible.builtin.shell:  |
         pkg install -y pfSense-pkg-openvpn-client-export

    - name: Reincarca pachetele pfSense
      ansible.builtin.shell:  |
         php /etc/rc.packages

    - name: Generez fisierul config.xml din template si il pun direct in pfSense
      ansible.builtin.template:
        src: ../templates/config.xml.j2
        dest: /cf/conf/config.xml

    - name: Reboot pfSense pentru aplicarea configuratiilor
      ansible.builtin.shell: /sbin/reboot
      async: 1
      poll: 0
